name: Main 🧠
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build
          cd docs && npm run build cd ..

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs/build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        id: publish
        if: ${{ env.deployment_status != 'failed' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Get changes from changelog
        if: ${{ steps.publish.outputs.type != 'none' }}
        run: |
          chmod +x scripts/getChange.sh
          ./scripts/getChange.sh ${{steps.publish.outputs.version}} CHANGELOG.md > CHANGELOG.txt

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        if: ${{ steps.publish.outputs.type != 'none' }}
        with:
          body_path: CHANGELOG.txt
          files: build/*
          tag_name: ${{steps.publish.outputs.version}}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
